### ISSUE TITLE
Migrate ha-tahoma to Overkiz integration in core

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#697]
Let's keep track of the PR's and the work we need to do, to get everything to core.

**2022.2**
- [x] Base PR + Sensor
- [x] Lock PR + platforms
- [x] Button entity
- [x] Number entity
- [x] Light platform
- [x] Small Overkiz refactor
- [x] Add unique ID to config flow
- [x] Scene platform
- [x] Binary sensor entity
- [x] Address feedback: full mypy strict typing
- [x] Move to Overkiz 1.1.0 (remove casting in coordinator)
- [x] Select entity
- [x] Address feedback: improve coordinator with Registry
- [x] Don't close HA session in Config Flow
- [x] Switch platform
- [x] Update sensor platform
- [x] Add missing binary sensors
- [x] Fix where model can be str(none)
- [x] Add missing buttons 
- [x] Move to constants
- [x] Add diagnostics support
- [x] Address feedback (https://github.com/home-assistant/core/pull/64000#discussion_r786654864)
- [x] Move logger `_LOGGER = logging.getLogger(__name__)` to const.py and import it
- [x] Cover platform
- [x] Address feedback: better config flows tests (https://github.com/home-assistant/core/pull/62640#discussion_r776278803)
- [x] Implement reauth
- [x] Add zeroconf discovery
- [x] Implement Somfy OAuth

**2022.3**
- [x] Siren platform 
- [x] Support StatelessAlarmController and StatelessExteriorHeating via switch
- [x] Chain RTS cover commands
- [x] Add Low Speed functionality

**2022.4**
- [x] Alarm Control Panel platform (rewrite to EntityDescription)

**Climate implementations**
- [x] AtlanticElectricalHeater
- [x] AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint https://github.com/home-assistant/core/pull/72790
- [x] AtlanticElectricalTowelDryer https://github.com/home-assistant/core/pull/73788
- [x] AtlanticHeatRecoveryVentilation https://github.com/home-assistant/core/pull/74015
- [x] AtlanticPassAPCHeatingAndCoolingZone
- [x] AtlanticPassAPCZoneControl
- [x] AtlanticPassAPCDHW
- [x] DimmerExteriorHeating (moved to number entity)
- [ ] EvoHomeController
- [ ] HeatingSetPoint
- [ ] HitachiAirToAirHeatPump https://github.com/home-assistant/core/pull/81743
- [ ] HitachiAirToWaterHeatingZone
- [x] SomfyHeatingTemperatureInterface (parlty migrated to select / number entity)
- [x] SomfyThermostat

**TODO (2022.5 +)**
- [x] Fix assumed state check
- [x] Add local (jailbreaked) support (needs Config Flow work + pyoverkiz work + tests)
- [ ] Water heater platform (one by one, and fully tested)
- [ ] Add tests for diagnostics feature
- [ ] Rewrite executions.get("") to have it typed
- [ ] Extend diagnostics (add history of events) and make it possible to get it per device.
- [x] Implement https://github.com/iMicknl/python-overkiz-api/pull/330
- [ ] Code quality: move cover entities back to a single file

**TODO (long term?)**
- [ ] Address feedback: less DRY in `async_setup_entry`  https://github.com/home-assistant/core/pull/62916#discussion_r780707184
- [x] Support low speed service (is this still required?)
- [ ] Raise Overkiz events in DataUpdateCoordinator (on failure etc.)
- [ ] Add battery sensor (like in current state_attributes implementation)
- [ ] Basic tests via setup.json definitions?
- [ ] Execute command service?

**Other**
- [ ] Merge core integration back to custom component (keep tahoma domain)
- [ ] Fix remaining issues in ha-tahoma repo

(+ make sure all documentation is ready on-time for the core publish)

**Comment by Quentame** [comment]
I've review all open `overkiz` core PRs, enjoy ;)
I can merge after they got fixed.

**Comment by iMicknl** [comment]
@Quentame <3, thanks! I hope to be a bit less busy in the coming weeks to add some more PR's!

**Comment by Quentame** [comment]
2022.12: AtlanticPassAPCHeatingAndCoolingZone - PR https://github.com/home-assistant/core/pull/78659 got merged

**Comment by Quentame** [comment]
2022.12: AtlanticPassAPCDHW - PR https://github.com/home-assistant/core/pull/78665 got merged

**Comment by Quentame** [comment]
2022.12: Add Brandt, Hexaom, SIMU & Ubiwizz as virtuals integrations of Overkiz - PR https://github.com/home-assistant/core/pull/79566 got merged

**Comment by Quentame** [comment]
2022.12: Add Overkiz AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint - PR https://github.com/home-assistant/core/pull/72790 got merged

**Comment by sanvalerius** [comment]
Interested in the "EvoHomeController", any update or estimated availability ?
I have it and can do some testings, currently I'm available to see the temperatures and set points of heating devices behind evohome. 

Thanks a lot for this heavy work !

**Comment by iMicknl** [comment]
@sanvalerius does EvoHomeController work in ha-tahoma?

**Comment by Quentame** [comment]
2022.12: Add Overkiz Hitachi DHW - PR https://github.com/home-assistant/core/pull/81536 got merged

**Comment by Quentame** [comment]
2022.12: Add Overkiz DomesticHotWaterProduction - PR https://github.com/home-assistant/core/pull/81538 got merged

**Comment by Quentame** [comment]
2022.12: Use same Overkiz (Atlantic) climate entity for 2 different ui widget name - PR https://github.com/home-assistant/core/pull/82955 got merged

**Comment by sanvalerius** [comment]
> @sanvalerius does EvoHomeController work in ha-tahoma?

Partially, on the "Overkiz" (official), I only get the room temperatures. 
On the "Tahoma Custom", I get the room temperatures, the "set-point temp" (that I can set to a new value), with thermostat lovelace cards as well.
the Evohome controller "appears" as an entity, but seems doesn't display the live status (alway in auto) and We can't interact with it (ie change the mode to "away" or "holidays")
